language: node_js
node_js:
  - "15"
cache:
  directories:
    - node_modules
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - yarn test
  - yarn build
after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info # Format frontend coverage
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage;cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi # Upload coverage/codeclimate.json
